name: Test

on:
  push

jobs:
  test:
    name: Autographing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: ANTLR4
        run: |
          antlr4 -Dlanguage=Python3 project/lang.g4 -visitor -o project/lang
      - name: Run tests
        run: python3 ./scripts/run_tests.py
